kind: pipeline
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64

node:
  cloud: oracle
  location: tokyo
  
trigger:
  branch:
  - master

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: gomodcache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:
  - name: build-docker
    image: docker:dind
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - docker login --username=cloverzrg -p $password
      - build_node=$(docker buildx create --use)
      - echo 'build node:'$build_node
      - docker buildx build --platform linux/arm64,linux/amd64 -t cloverzrg/wechat-work-message-push-go:latest --push .
      - docker buildx rm $build_node

