kind: pipeline
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64


node:
  cloud: oracle
  location: tokyo
  
trigger:
  branch:
  - master

steps:
#  - name: go-build
#    image: golang:alpine
#    commands:
#      - go env
#      - apk update && apk upgrade && apk add --no-cache git
#      - go mod download
#      - buildflags="-X 'main.BuildTime=`date`' -X 'main.GitHead=`git rev-parse --short HEAD`' -X 'main.GoVersion=$(go version)'" && go build -ldflags "$buildflags" -o wechat-work-message-push-go
#      - ./wechat-work-message-push-go -v
#
#  - name: docker-build
#    image: plugins/docker
#    settings:
#      repo:  cloverzrg/wechat-work-message-push-go
#      tags: latest
#      username:
#        from_secret: dockerhub-username
#      password:
#        from_secret: dockerhub-password

  - name: build-docker
    image: docker:dind
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - docker login --username=cloverzrg -p $password
      - build_node=$(docker buildx create --use)
      - echo 'build node:'$build_node
      - docker buildx build f Dockerfilev2 --platform linux/arm64,linux/amd64 -t cloverzrg/wechat-work-message-push-go:latest --push .
      - docker buildx rm $build_node

