// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetItemBrandAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemBrandAllRequest) Reset()         { *m = GetItemBrandAllRequest{} }
func (m *GetItemBrandAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemBrandAllRequest) ProtoMessage()    {}
func (*GetItemBrandAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *GetItemBrandAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemBrandAllRequest.Unmarshal(m, b)
}
func (m *GetItemBrandAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemBrandAllRequest.Marshal(b, m, deterministic)
}
func (m *GetItemBrandAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemBrandAllRequest.Merge(m, src)
}
func (m *GetItemBrandAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemBrandAllRequest.Size(m)
}
func (m *GetItemBrandAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemBrandAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemBrandAllRequest proto.InternalMessageInfo

type GetItemBrandAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemBrandAllResponse) Reset()         { *m = GetItemBrandAllResponse{} }
func (m *GetItemBrandAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemBrandAllResponse) ProtoMessage()    {}
func (*GetItemBrandAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *GetItemBrandAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemBrandAllResponse.Unmarshal(m, b)
}
func (m *GetItemBrandAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemBrandAllResponse.Marshal(b, m, deterministic)
}
func (m *GetItemBrandAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemBrandAllResponse.Merge(m, src)
}
func (m *GetItemBrandAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemBrandAllResponse.Size(m)
}
func (m *GetItemBrandAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemBrandAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemBrandAllResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetItemBrandAllRequest)(nil), "api.GetItemBrandAllRequest")
	proto.RegisterType((*GetItemBrandAllResponse)(nil), "api.GetItemBrandAllResponse")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92,
	0xe0, 0x12, 0x73, 0x4f, 0x2d, 0xf1, 0x2c, 0x49, 0xcd, 0x75, 0x2a, 0x4a, 0xcc, 0x4b, 0x71, 0xcc,
	0xc9, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x92, 0xe4, 0x12, 0xc7, 0x90, 0x29, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0x0a, 0xe5, 0x62, 0x75, 0xcf, 0xcf, 0x4f, 0x29, 0x16, 0xf2, 0xe1,
	0xe2, 0x47, 0x53, 0x23, 0x24, 0xad, 0x07, 0xb2, 0x01, 0xbb, 0x99, 0x52, 0x32, 0xd8, 0x25, 0x21,
	0xc6, 0x26, 0xb1, 0x81, 0xdd, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x27, 0xc5, 0x09,
	0xa8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodsClient is the client API for Goods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodsClient interface {
	GetItemBrandAll(ctx context.Context, in *GetItemBrandAllRequest, opts ...grpc.CallOption) (*GetItemBrandAllResponse, error)
}

type goodsClient struct {
	cc *grpc.ClientConn
}

func NewGoodsClient(cc *grpc.ClientConn) GoodsClient {
	return &goodsClient{cc}
}

func (c *goodsClient) GetItemBrandAll(ctx context.Context, in *GetItemBrandAllRequest, opts ...grpc.CallOption) (*GetItemBrandAllResponse, error) {
	out := new(GetItemBrandAllResponse)
	err := c.cc.Invoke(ctx, "/api.Goods/GetItemBrandAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServer is the server API for Goods service.
type GoodsServer interface {
	GetItemBrandAll(context.Context, *GetItemBrandAllRequest) (*GetItemBrandAllResponse, error)
}

// UnimplementedGoodsServer can be embedded to have forward compatible implementations.
type UnimplementedGoodsServer struct {
}

func (*UnimplementedGoodsServer) GetItemBrandAll(ctx context.Context, req *GetItemBrandAllRequest) (*GetItemBrandAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemBrandAll not implemented")
}

func RegisterGoodsServer(s *grpc.Server, srv GoodsServer) {
	s.RegisterService(&_Goods_serviceDesc, srv)
}

func _Goods_GetItemBrandAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemBrandAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).GetItemBrandAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Goods/GetItemBrandAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).GetItemBrandAll(ctx, req.(*GetItemBrandAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Goods_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Goods",
	HandlerType: (*GoodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemBrandAll",
			Handler:    _Goods_GetItemBrandAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
